### ISSUE TITLE
Schema Review

### ISSUE THREAD

**Issue by juliajykim** [EddyMarshall/Conduit#2]
# Database Schema

- [x] Contains correct datatypes
- [x]  Contains appropriate constraints/details
    - [x]  primary key
    - [x]  not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
    - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

### Comments
- [x] on Medium, users can reply to comments: responses table needs parent_response_id. Look reddit project for example(W7D5)
- [x] for bonus feature, having joins table between tags and stories will facilitate many to many relation
- [x] can user claps to both stories and comments? then consider having polymorphic association for claps table. Look at ArtShare project(W6D4) for the reference

**Comment by EddyMarshall** [comment]
Heya, I added that polymorphic association for claps. Good spot.
